###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: phpapi-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=apiphp
        - MYSQL_DATABASE=apiphp
        - MYSQL_USER=apiphp
        - MYSQL_PASSWORD=apiphp
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: phpapi-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: phpapi-php-fpm
      working_dir: /application
      environment:
        XDEBUG_CONFIG: "remote_host=docker.for.mac.localhost"
        PHP_IDE_CONFIG: "serverName=docker"

      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

